# Generated by Django 4.1 on 2022-08-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cetivcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_Cetivcation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CityJop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_jop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kindjop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookingJop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brith_date', models.DateField()),
                ('experince', models.IntegerField(max_length=4)),
                ('mobile_No', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=100)),
                ('Cetivcation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jop_Cetivcation', to='jop.cetivcation')),
                ('City_jop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jop_City', to='jop.cityjop')),
                ('Kindjop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jop_kind', to='jop.kindjop')),
            ],
        ),
    ]
