# Generated by Django 4.1 on 2022-08-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookingjop',
            name='files',
            field=models.FileField(default=1, upload_to='jopfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='Cetivcation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jop_Cetivcation', to='jop.cetivcation', verbose_name='الموهل '),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='City_jop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jop_City', to='jop.cityjop', verbose_name='مدينه الوظيفة'),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='Email',
            field=models.EmailField(max_length=100, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='Kindjop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jop_kind', to='jop.kindjop', verbose_name='اسم الوظيفة'),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='brith_date',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='experince',
            field=models.IntegerField(verbose_name='سنوات الخبرة '),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='mobile_No',
            field=models.CharField(max_length=13, verbose_name='رقم الجوال '),
        ),
        migrations.AlterField(
            model_name='lookingjop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الموظف '),
        ),
    ]
