# Generated by Django 4.1 on 2022-08-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='blog',
        ),
    ]
