# Generated by Django 4.1 on 2022-08-13 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_created=True)),
                ('course_name', models.CharField(max_length=100)),
                ('hours', models.IntegerField(default=0)),
                ('course_lesson', models.IntegerField(default=0)),
                ('image_course', models.ImageField(upload_to='image_course')),
                ('summary_course', models.TextField(max_length=500)),
                ('course_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='gatogery_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_created=True, null=True)),
                ('title_gatogery', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_longTime', models.IntegerField(default=0)),
                ('lesson_content', models.TextField(max_length=500)),
                ('lesson_homework', models.TextField(max_length=1000)),
                ('lesson_video', models.FileField(upload_to='video_lesson')),
                ('course_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_gatogery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.gatogery_course'),
        ),
        migrations.AddField(
            model_name='courses',
            name='user_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(auto_created=True)),
                ('comment', models.TextField(max_length=500)),
                ('comment_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
    ]
