# Generated by Django 4.1 on 2022-08-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_comment_comment_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_gatogery',
        ),
        migrations.AddField(
            model_name='courses',
            name='gatogery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_gatogery', to='courses.gatogery_course'),
        ),
    ]
